# Github can't run jekyll to build pages, refer to the link.
# http://stackoverflow.com/questions/8104183/unable-to-run-jekyll

#---
#auto        : false
#lsi         : false
#pygments    : true
#permalink   : none
#markdown    : maruku
#
#maruku:
#    use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

#safe:        false
#auto:        false
#server:      false
#server_port: 4000
#baseurl:   / 
#url: http://localhost:4000

#source:      .
#destination: ./_site
#plugins:     ./_plugins
   
